apiVersion: v1
kind: ConfigMap
metadata:
  name: rollup-config
data:
  DATABASE_URL: "postgres://postgres:password@db:5432/rollup"
  REDIS_URL: "redis://redis:6379"
  ETH_RPC_URL: "https://eth-sepolia.g.alchemy.com/v2/RZPzSZ3OqncgXm0kF_2bF"
  ROLLUP_CONTRACT_ADDRESS: "0xf5301075fC54dC20893f8Dbd0832274Fe9767b4e"
  BLOCK_SIZE: "5"
  PROCESS_INTERVAL: "5000"
  DA_HOST: "http://da-layer:4000"
