apiVersion: v1
kind: Secret
metadata:
  name: rollup-secret
type: Opaque
stringData:
  ETH_PRIVATE_KEY: "7847d18e38e3301e8808ef029c76d7a3a03ffaee064421d12f68ae7e0479de04"
  POSTGRES_PASSWORD: "password"
